"""fix quiz type enum and minor model tweaks

Revision ID: 35a332204be4
Revises: d22dd0cd6a20
Create Date: 2026-07-04 17:18:09.920382

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '35a332204be4'
down_revision: Union[str, Sequence[str], None] = 'd22dd0cd6a20'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('password_reset_tokens') as batch_op:
        batch_op.alter_column('used', existing_type=sa.BOOLEAN(), nullable=False)
    op.add_column('user_vocab_notes', sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_vocab_notes', 'updated_at')
    with op.batch_alter_table('password_reset_tokens') as batch_op:
        batch_op.alter_column('used', existing_type=sa.BOOLEAN(), nullable=True)
    # ### end Alembic commands ###
