// ---- Enums / Union types mirroring backend ----

export type SubscriptionTier = "free" | "starter" | "plus" | "pro";
export type CEFRLevel = "A1" | "A2" | "B1" | "B2" | "C1";
export type CardStatus = "new" | "learning" | "reviewing" | "mastered";
export type QuizType = "translate" | "fill-blank" | "multiple-choice" | "conjugate" | "mixed";

// ---- Domain models (mirrors SQLAlchemy models) ----

export interface User {
  id: number;
  email: string;
  name: string;
  subscription_tier: SubscriptionTier;
  trial_ends_at: string | null;
  daily_streak: number;
  last_active_date: string | null;
  target_level: CEFRLevel;
  settings: UserSettings;
  created_at: string;
}

export interface UserSettings {
  reminders_enabled: boolean;
  daily_goal_cards: number;
  quiz_size: number;
}

export interface Lesson {
  id: number;
  level: CEFRLevel;
  unit: number;
  order: number;
  title: string;
  description: string | null;
  content: string | null;
  topics: string[] | null;
  prerequisite_lesson_id: number | null;
  created_at: string;
}

export interface VocabEntry {
  id: number;
  lesson_id: number;
  german: string;
  english: string;
  part_of_speech: string | null;
  gender: string | null;
  plural_form: string | null;
  example_sentence: string | null;
  audio_url: string | null;
  difficulty_rank: number;
}

export interface GrammarTopic {
  id: number;
  slug: string;
  title: string;
  level: CEFRLevel;
  content: string | null;
  examples: Record<string, string> | null;
  related_lesson_ids: number[] | null;
}

export interface SRSState {
  id: number;
  user_id: number;
  vocab_entry_id: number;
  easiness_factor: number;
  interval_days: number;
  repetitions: number;
  lapses: number;
  next_review_at: string;
  last_reviewed_at: string | null;
  status: CardStatus;
}

export interface QuizResult {
  id: number;
  user_id: number;
  quiz_type: QuizType;
  score_pct: number;
  questions_total: number;
  questions_correct: number;
  missed_vocab_ids: number[] | null;
  created_at: string;
}

export interface LessonProgress {
  id: number;
  user_id: number;
  lesson_id: number;
  completed_at: string | null;
  quiz_score: number | null;
}

export interface UserVocabNote {
  id: number;
  user_id: number;
  german: string;
  english: string;
  notes: string | null;
  created_at: string;
  updated_at: string;
}

// ---- Curriculum types ----

export interface CurriculumLevel {
  level: string;
  title: string;
  lesson_count: number;
  completed_count: number;
}

export interface LessonListItem {
  id: number;
  title: string;
  unit: number;
  order: number;
  topics: string[];
  completed: boolean;
}

export interface LessonDetail {
  lesson: {
    id: number;
    title: string;
    level: string;
    unit: number;
    order: number;
    description: string | null;
    content: string | null;
    topics: string[];
    prerequisite_lesson_id: number | null;
    created_at: string;
  };
  vocabulary: VocabEntry[];
  exercises: Record<string, unknown>[];
  grammar_topics: {
    id: number;
    slug: string;
    title: string;
    level: string;
    content: string | null;
    examples: Record<string, string>[];
  }[];
}

// ---- Dashboard aggregate (computed by backend) ----

export interface DashboardData {
  streak: number;
  cards_due_today: number;
  avg_quiz_score: number;
  level_progress_pct: number;
  continue_lesson: {
    id: number;
    title: string;
    level: string;
    unit: number;
    progress_pct: number;
  } | null;
  recent_activity: {
    type: string;
    description: string;
    timestamp: string;
  }[];
  weakest_words: {
    id: number;
    german: string;
    english: string;
    lapses: number;
  }[];
}

// ---- Quiz session (generated by backend) ----

export interface QuizSession {
  session_id: string;
  questions: QuizQuestion[];
}

export interface QuizQuestion {
  id: number | string;
  type: QuizType;
  prompt: string;
  options?: string[];
  answer?: string;
  hint?: string;
}

// ---- Plans / pricing ----

export interface Plan {
  tier: SubscriptionTier;
  levels: CEFRLevel[];
  monthly_price: number;
  annual_price: number;
  features: string[];
}

// ---- Auth request/response shapes ----

export interface LoginRequest {
  email: string;
  password: string;
}

export interface SignupRequest {
  name: string;
  email: string;
  password: string;
}

export interface AuthResponse {
  user: User;
  token: string;
}
