import type { Config } from "tailwindcss";

const config: Config = {
  content: [
    "./app/**/*.{js,ts,jsx,tsx,mdx}",
    "./components/**/*.{js,ts,jsx,tsx,mdx}",
    "./contexts/**/*.{js,ts,jsx,tsx,mdx}",
    "../packages/shared/ui/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        /* Canonical names */
        "surface-1": "var(--color-surface-1)",
        "surface-2": "var(--color-surface-2)",
        "surface-3": "var(--color-surface-3)",
        "bg-primary": "var(--color-background-primary)",
        "bg-secondary": "var(--color-background-secondary)",
        "text-primary": "var(--color-text-primary)",
        "text-secondary": "var(--color-text-secondary)",
        "text-tertiary": "var(--color-text-tertiary)",
        muted: "var(--color-text-muted)",
        "border-subtle": "var(--color-border-subtle)",
        "border-strong": "var(--color-border-strong)",
        "border-focus": "var(--color-border-focus)",
        accent: "var(--color-accent)",
        "accent-light": "var(--color-accent-light)",
        "accent-dark": "var(--color-accent-dark)",
        "accent-text": "var(--color-accent-text)",
        "hover-bg": "var(--color-hover-bg)",
        "active-bg": "var(--color-active-bg)",
        "active-text": "var(--color-active-text)",
        success: "var(--color-success)",
        warning: "var(--color-warning)",
        error: "var(--color-error)",
        info: "var(--color-info)",
        skeleton: "var(--color-skeleton)",
        /* Legacy aliases */
        page: "var(--color-page-bg)",
        card: "var(--color-card-bg)",
        border: "var(--color-border)",
      },
      fontSize: {
        "display-lg": ["var(--type-display-lg)", { lineHeight: "1.1" }],
        "display-md": ["var(--type-display-md)", { lineHeight: "1.2" }],
        "heading-lg": ["var(--type-heading-lg)", { lineHeight: "1.3" }],
        "heading-md": ["var(--type-heading-md)", { lineHeight: "1.3" }],
        "heading-sm": ["var(--type-heading-sm)", { lineHeight: "1.4" }],
        "title-md": ["var(--type-title-md)", { lineHeight: "1.4" }],
        "body-md": ["var(--type-body-md)", { lineHeight: "1.5" }],
        "body-sm": ["var(--type-body-sm)", { lineHeight: "1.5" }],
        "label-md": ["var(--type-label-md)", { lineHeight: "1.4" }],
        "label-sm": ["var(--type-label-sm)", { lineHeight: "1.3" }],
        caption: ["var(--type-caption)", { lineHeight: "1.2" }],
        "mono-md": ["var(--type-mono-md)", { lineHeight: "1.5" }],
        /* Legacy aliases */
        hero: ["var(--text-hero)", { lineHeight: "1.1" }],
        "page-title": ["var(--text-page-title)", { lineHeight: "1.3" }],
        micro: ["var(--text-micro)", { lineHeight: "1.2" }],
      },
      spacing: {
        /* Canonical scale */
        "1": "var(--space-1)",
        "2": "var(--space-2)",
        "3": "var(--space-3)",
        "4": "var(--space-4)",
        "5": "var(--space-5)",
        "6": "var(--space-6)",
        "7": "var(--space-7)",
        "8": "var(--space-8)",
        "9": "var(--space-9)",
        "10": "var(--space-10)",
        /* Legacy aliases */
        "4xs": "var(--space-1)",
        "3xs": "var(--space-2)",
        "2xs": "var(--space-3)",
        xs: "var(--space-4)",
        sm: "var(--space-5)",
        md: "var(--space-6)",
        lg: "var(--space-7)",
        xl: "var(--space-8)",
      },
      borderRadius: {
        /* Canonical */
        xs: "var(--radius-xs)",
        sm: "var(--radius-sm)",
        md: "var(--radius-md)",
        lg: "var(--radius-lg)",
        xl: "var(--radius-xl)",
        pill: "var(--radius-pill)",
      },
      boxShadow: {
        /* Canonical elevation */
        "elevation-0": "var(--elevation-0)",
        "elevation-1": "var(--elevation-1)",
        "elevation-2": "var(--elevation-2)",
        "elevation-3": "var(--elevation-3)",
        "elevation-4": "var(--elevation-4)",
        /* Canonical shadow */
        "shadow-sm": "var(--shadow-sm)",
        "shadow-md": "var(--shadow-md)",
        "shadow-lg": "var(--shadow-lg)",
        "shadow-xl": "var(--shadow-xl)",
        /* Legacy aliases */
        card: "var(--shadow-card)",
        dropdown: "var(--shadow-dropdown)",
        glow: "var(--shadow-glow)",
        ring: "var(--shadow-ring)",
      },
      zIndex: {
        base: "var(--z-base)",
        dropdown: "var(--z-dropdown)",
        sticky: "var(--z-sticky)",
        overlay: "var(--z-overlay)",
        modal: "var(--z-modal)",
        toast: "var(--z-toast)",
        tooltip: "var(--z-tooltip)",
      },
      transitionDuration: {
        fast: "var(--duration-fast)",
        normal: "var(--duration-normal)",
        slow: "var(--duration-slow)",
      },
      transitionTimingFunction: {
        standard: "ease-out",
        decelerate: "cubic-bezier(0, 0, 0.2, 1)",
        accelerate: "cubic-bezier(0.4, 0, 1, 1)",
        emphasized: "cubic-bezier(0.4, 0, 0.2, 1.5)",
      },
    },
  },
  plugins: [],
};

export default config;
